# Shopify App Configuration

name = "commercive"
client_id = "813fd5f2b7ad1046bd3bb049b86f9dfe"
application_url = "https://app.commercive.co"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_fulfillments,write_fulfillments,read_inventory,write_inventory,read_locations"

[auth]
redirect_urls = [
  "https://app.commercive.co/auth/callback",
  "https://app.commercive.co/auth/shopify/callback",
  "https://app.commercive.co/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[app_proxy]
url = "https://app.commercive.co"
subpath = "apps"
prefix = "apps"
